import fs from "node:fs";
import path from "node:path";

type RemoteAssetKind =
  | "animal-happy"
  | "animal-sad"
  | "reward"
  | "audio"
  | "sticker"
  | "bonus";

type RemoteAsset = {
  id: string;
  kind: RemoteAssetKind;
  path: string;
  sizeBytes: number;
  proDownload: boolean;

  animalId?: string;
  animalName?: string;
  mood?: "happy" | "sad";

  rewardId?: string;
  rewardTitle?: string;
  rewardAnimalName?: string;

  audioKey?: string;
};

const rootDir = process.cwd();
const remoteAssetsSourceDir = path.join(rootDir, "remote-assets-source");
const outputFilePath = path.join(rootDir, "src", "services", "assets", "remoteAssetManifest.ts");

function titleCase(value: string) {
  return value
    .split(/[\s_-]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function slugify(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function getFilesRecursively(dir: string): string[] {
  let results: string[] = [];
  if (!fs.existsSync(dir)) return results;
  const list = fs.readdirSync(dir);
  for (const file of list) {
    const fullPath = path.join(dir, file);
    const stat = fs.statSync(fullPath);
    if (stat && stat.isDirectory()) {
      results = results.concat(getFilesRecursively(fullPath));
    } else {
      if (file !== ".gitkeep") {
        results.push(fullPath);
      }
    }
  }
  return results;
}

function main() {
  const assets: RemoteAsset[] = [];

  const folders: Array<{ dirName: string; kind: RemoteAssetKind }> = [
    { dirName: "data/generated/animals/happy", kind: "animal-happy" },
    { dirName: "data/generated/animals/sad", kind: "animal-sad" },
    { dirName: "data/generated/rewards", kind: "reward" },
    { dirName: "data/audio", kind: "audio" },
    { dirName: "data/stickers", kind: "sticker" },
    { dirName: "data/bonus", kind: "bonus" },
  ];

  for (const folder of folders) {
    const fullDir = path.join(remoteAssetsSourceDir, folder.dirName);
    const files = getFilesRecursively(fullDir);

    for (const file of files) {
      const relativePath = path.relative(remoteAssetsSourceDir, file).replace(/\\/g, "/");
      const stat = fs.statSync(file);
      const filename = path.basename(file);

      const asset: RemoteAsset = {
        id: "",
        kind: folder.kind,
        path: relativePath,
        sizeBytes: stat.size,
        proDownload: true,
      };

      if (folder.kind === "animal-happy" || folder.kind === "animal-sad") {
        const match = filename.match(/^(animal_\d+)_(.+)\.png$/i);
        if (match) {
          const animalId = match[1];
          const animalNameRaw = match[2];
          const animalName = titleCase(animalNameRaw);
          const mood = folder.kind === "animal-happy" ? "happy" : "sad";
          
          asset.animalId = animalId;
          asset.animalName = animalName;
          asset.mood = mood;
          asset.id = `animal-${animalId.replace(/_/g, "-")}-${slugify(animalNameRaw)}-${mood}`;
        } else {
          asset.id = `animal-${slugify(filename)}`;
        }
      } else if (folder.kind === "reward") {
        const match = filename.match(/^(reward_\d+)_(.+?)_(.+)\.png$/i);
        if (match) {
          const rewardId = match[1];
          const animalNameRaw = match[2];
          const labelRaw = match[3];
          
          asset.rewardId = rewardId;
          asset.rewardAnimalName = titleCase(animalNameRaw);
          asset.rewardTitle = titleCase(labelRaw);
          asset.id = `reward-${rewardId.replace(/_/g, "-")}-${slugify(animalNameRaw)}-${slugify(labelRaw)}`;
        } else {
          asset.id = `reward-${slugify(filename)}`;
        }
      } else if (folder.kind === "audio") {
        const audioKey = slugify(path.basename(filename, path.extname(filename)));
        asset.audioKey = audioKey;
        asset.id = `audio-${audioKey}`;
      } else {
        asset.id = `${folder.kind}-${slugify(path.basename(filename, path.extname(filename)))}`;
      }

      assets.push(asset);
    }
  }

  // Generate output file content
  const manifestContent = `// This file is auto-generated by scripts/generateRemoteAssetManifest.ts.
// Do not modify manually.

import type { RemoteAsset } from "./remoteAssetTypes";

export const REMOTE_ASSETS: RemoteAsset[] = ${JSON.stringify(assets, null, 2)};

export const PRO_UNLOCK_REMOTE_ASSETS = REMOTE_ASSETS.filter(
  (asset) => asset.proDownload
);

export const REMOTE_ASSET_BY_ID = Object.fromEntries(
  REMOTE_ASSETS.map((asset) => [asset.id, asset])
);

// Group helpers
export const REMOTE_ASSETS_BY_ANIMAL_ID = REMOTE_ASSETS.reduce<Record<string, RemoteAsset[]>>(
  (acc, asset) => {
    if (asset.animalId) {
      acc[asset.animalId] = acc[asset.animalId] || [];
      acc[asset.animalId].push(asset);
    }
    return acc;
  },
  {}
);

export const REMOTE_REWARDS_BY_ANIMAL_NAME = REMOTE_ASSETS.reduce<Record<string, RemoteAsset[]>>(
  (acc, asset) => {
    if (asset.kind === "reward" && asset.rewardAnimalName) {
      const name = asset.rewardAnimalName;
      acc[name] = acc[name] || [];
      acc[name].push(asset);
    }
    return acc;
  },
  {}
);
`;

  // Ensure output directory exists
  fs.mkdirSync(path.dirname(outputFilePath), { recursive: true });
  fs.writeFileSync(outputFilePath, manifestContent, "utf8");

  console.log(`Generated manifest at ${outputFilePath}`);
  console.log(`Tracked ${assets.length} remote assets.`);
}

main();
